### ISSUE TITLE
We need to add code that generates the ELS_ID from the Subject_ID_Timepoint

### ISSUE THREAD

**Issue by rachelweisenburger** [gifuni/COVID_ELS#2]

**Comment by gifuni** [comment]
Ok I can take care of that. Could you point me to:
1) A file that will serve as input.
2) The appearance of original variable
3) The desired appearance and format of the output

**Comment by rachelweisenburger** [comment]
Example of a file that will serve as input (the REDCap export, see attached).
Appearance of the original variable (see attached, "record_id"): 001-T3
[ELST3ChildQuestionna_DATA_2020-04-15_2038.xlsx](https://github.com/gifuni/COVID_ELS/files/4506583/ELST3ChildQuestionna_DATA_2020-04-15_2038.xlsx)

Desired appearance and format see "example" excel sheet.
[example.xlsx](https://github.com/gifuni/COVID_ELS/files/4506587/example.xlsx)

**Comment by gifuni** [comment]
InitialString <- "002-T2"
First3chr <- substr(InitialString,1,3)
id <- as.numeric(First3chr)

**Comment by gifuni** [comment]
You need to embed it in a function, then apply the function to your column. 
conversion <- function(X) {
First3chr <- substr(InitialString,1,3)
Y <- as.numeric(First3chr)
return(Y)
}
