### ISSUE TITLE
Sex and age covariates for the CHILD data

### ISSUE THREAD

**Issue by gifuni** [gifuni/COVID_ELS#6]
In the import script, it would be very useful to have the age (at COVID timepoint) and the sex of each participant in the resulting CHILD dataframe.

**Comment by rachelweisenburger** [comment]
Age will need to be manually added after export due to date of birth being PHI. I will add sex!

**Comment by rachelweisenburger** [comment]
see most recent pull request! I added ELS_DEMO to the Import script, it contains age at COVID and child sex.

**Comment by gifuni** [comment]
Thanks! Pull request has been merged!
